### ISSUE TITLE
Django の web API 調査

### ISSUE THREAD

**Issue by ytakashina** [ytakashina/iotoilet#2]
参考 URL: https://qiita.com/kimihiro_n/items/86e0a9e619720e57ecd8

GanttStart: 2019-06-11 9:00
GanttDue: 2019-06-11 13:00

**Comment by tkawa0419** [comment]
富田さんがあげてくれた
https://qiita.com/kimihiro_n/items/86e0a9e619720e57ecd8
を見ながら動作が記載通りにいくかふたりで検証している

**Comment by ytakashina** [comment]
Done
