### ISSUE TITLE
AWS EC2 の設定

### ISSUE THREAD

**Issue by ytakashina** [ytakashina/iotoilet#3]
GanttStart: 2019-06-11 13:00
GanttDue: 2019-06-11 17:00

**Comment by ytakashina** [comment]
検証環境については岩田君がやってくれた
本番環境は「EC2本番サーバー立てる #52」

**Comment by SoheiIwata** [comment]
１．puTTYでEC2サーバーに接続
https://qiita.com/s_runoa/items/156f3fa67c82e9cd9f42
を参照

サーバーの起動　この項が終わったら別のページを参考に処理を行う

注意点
・.bash_profileに追記する　この項で行う処理
$vim .bash_profile
上のコマンドを入れて .bash_projectに以下を追記
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
・サーバーの起動の項でうまく動かない場合
EC2は最初ポート22しか開いていない
AWSコンソールのEC2でセキュリティグループを編集して必要なポートを開ける

２．ローカルでDjango Rest Frameworkを使ったプロジェクトを作成
https://qiita.com/kimihiro_n/items/86e0a9e619720e57ecd8
を参照

３．EC2でDjango Rest Frameworkを使えるようにする
pip install django
pip install djangorestframework
pip install django-filter 
puTTYで上のコマンドを入れる

4．ローカルで作ったプロジェクトをEC2に入れる
WinSCPをインストールして利用
https://dev.classmethod.jp/cloud/aws/winscp-amazon/
を参照
EC2の秘密鍵が必要
設定→認証→認証条件の秘密鍵

**Comment by TomoeAsagami** [comment]
gj
