### ISSUE TITLE
トイレの開け閉めを検知するための仕組みを考える

### ISSUE THREAD

**Issue by tkawa0419** [ytakashina/iotoilet#31]
GanttStart: 2019-06-11 9:00
GanttDue: 2019-06-11 12:00

**Comment by tkawa0419** [comment]
GantStart 2019-06-11 11:00
GantDue 2019-06-11 12:00

**Comment by tkawa0419** [comment]
明るさを一定時間ごとに取得し、db上に送信する。
余裕があれば加速度センサーと併用し、正確性を向上したい

**Comment by ytakashina** [comment]
Done
