### ISSUE TITLE
Djangoでセンサーデータから開閉状況を設定する方法の検討

### ISSUE THREAD

**Issue by daisukefuku** [ytakashina/iotoilet#35]
GanttStart: 2019-06-11 14:00
GanttDue: 2019-06-11 15:00

**Comment by ytakashina** [comment]
- 「今個室が開いているか」をどう判断するか
      1. 明るさのデータを一定間隔ごとに DB にためる
      2. HTTP リクエストがあってから最新のレコードを見る
      3. 閾値で○○以上(例:3)の明るさがあったら個室が埋まっていると判断
    - 「個室が使われている時間」をどう計算するか
      1. 明るさのデータを一定間隔ごとに DB にためる
      2. HTTP リクエストがあってから最新の数件のレコードを見る
      3. 閾値で○○以上(例:3)の明るさがあったら個室が埋まっていると判断
      4. 直近の連続した「個室が埋まっている」レコードから埋まっている時間を計算
